version: '3'

services:
  lap:
    image: fauria/lap:latest
    restart: always
    ports:
      - '${PORTBASE}80:80'
    volumes:
      - html:/var/www/html

  service:
    build: ./service
    restart: always
    ports: 
      - "${PORTBASE}88:80"
    environment:
      - CMS=${CMS}
      - URL=${URL}
      - TG_TOKEN=${TG_TOKEN}
      - TG_GROUP=${TG_GROUP}
      - TOKEN_SERVICE=${TOKEN_SERVICE}
    
volumes:
  html: